[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]
ffi = false #only set to true when using foundry devops

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
